repos:
  - repo: local
    hooks:
      - id: treefmt
        name: treefmt
        entry: treefmt --fail-on-change
        exclude: "^$"
        language: system
        pass_filenames: true
        stages:
          - pre-commit
        types:
          - file
        verbose: false
